
CREATE DATABASE IF NOT EXISTS Echofy CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tts_ocr;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  token VARCHAR(500),
  
);
